#!/usr/bin/env python

import sys

from rqt_quaternion_view.quaternion_view import QuaternionView
from rqt_gui.main import Main

plugin = 'rqt_quaternion_view'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
